name: CI


on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: nikil-sigmoid
          repo: deployment_demo1
          github_token: ${{ secrets.PAT }}
          workflow_file_name: main.yml
